# .github/workflows/release.yml

# Name of the workflow
name: Release Go Project

# Controls when the action will run. 
# This workflow runs manually and when a new tag is pushed.
on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v', e.g., v1.0, v1.1.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "release" job
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Add this permissions block
    permissions:
      contents: write # This is required to create a release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Specify your Go version

      # Step 3: Run the GoReleaser action
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # The version of GoReleaser to use
          version: latest
          # The arguments to pass to GoReleaser
          args: release --clean
        env:
          # The GITHUB_TOKEN is a special token provided by GitHub Actions
          # It's required to create the release on your repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

